### ISSUE TITLE
Shifter Update Progress Report

### ISSUE THREAD

**Issue by ApolloX939** [TurkeyMcMac/shifter_tool#1]
Hey there so as you may or may not have noticed [my repo](https://github.com/Beanzilla/shifter_tool).

Here's what my goal is for this thing till I make a PR...

- [x] Modes (This will allow your original features to be kept and allow me to add the new feature of "teleport")
- [x] Teleport (Allow a player to essentially "capture" a node/block then move to a new place and "release" said node/block)
- [x]  Add Protection validation on teleport.
- [x] Get [area_containers](https://github.com/TurkeyMcMac/area_containers) to work properly in teleport.

As you may notice Teleport isn't done yet... and at it's current state it simply reports the tool can't do anything in that mode. (Which right now is correct)

Yes you may be thinking... "Okay wise guy, how will you handle my [area_containers](https://github.com/TurkeyMcMac/area_containers) while someone is carrying or moving the container?"

Simple really, instead of "capture" meaning the block now is stored internally we simply record it's position, then at the new location we verify we can move out of old location and to the new location, if the protection passes then the block is essentially ordered to the new position, and we fill the old with "default:air" (Thus teleporting the block)

^^ The above sounds simple in words but it took me a while to even figure out how to do the mode shifting. (I based it off of [1](https://github.com/minetest-mods/technic/blob/master/technic/tools/mining_drill.lua#L266-L287) and [2](https://github.com/minetest-mods/technic/blob/master/technic/tools/mining_drill.lua#L312-L332))

So when will this thing be ready for you to test it? (Soon, If I had to guess, it should be ready some time within the next few days)

There you have it, my report to you on what new and baffling ideas I have come up with. :)

**Comment by ApolloX939** [comment]
Okay well it appears metadata is setup correctly so everything acts like the original block teleported.

Except for a new issue...

Using [area_containers](https://github.com/TurkeyMcMac/area_containers) creates a new container rather than reusing the metadata from the old container. (Not sure if that's an issue with my teleport or if it's an issue with area_containers.

**Comment by ApolloX939** [comment]
If you want you can get my master branch of [my repo](https://github.com/Beanzilla/shifter_tool) and try it out yourself.

I'm free to and ideas/solutions to fixing the [area_containers](https://github.com/TurkeyMcMac/area_containers) bug.

**Comment by TurkeyMcMac** [comment]
Your design sounds good. If I were you I might put the teleporter in a separate mod, since it serves a separate function. (You could still base the code on shifter_tool, of course.)

Regarding the bug, I left a comment on one of the area_containers issues. The code needs to remove the old node before adding the new. If I read the code correctly, I don't think it does it this way yet.

I can't test the code at the moment. I can test it next week.

**Comment by ApolloX939** [comment]
Currently I was thinking of just updating shifter_tool, as since teleporting a block essentially moves it and shifting a block also moves it. (I just see the method at which it is achieved is different, same action just the way it's done)

But if you want me to put it into a separate mod that's fine with me too. (Just figured a PR and then your mod would be updated with the new feature, then you'd release an update on contentdb and the new feature)

It just means I'd need to publish onto ContentDB the separate mod... perhaps when I release it you could then link to it on the ContentDB, and I'll cross link it so it mentions shifter_tool. (Essentially promote each mod)

Just :+1: if you want me to proceed making it a separate mod. (I think you'd prefer it so I will assume that I need to get my code separated from your's, since right now everything is pressed together into a grilled cheese, no wait that's my lunch. :) )

**Comment by ApolloX939** [comment]
Or not I think I will go ahead and just release the mod separately...

I'll give the ContentDB link for if you want to promote my mod on your mod's page too.

**Comment by ApolloX939** [comment]
Links:
* [github](https://github.com/Beanzilla/teleporter_tool)
* `[![ContentDB](https://content.minetest.net/packages/ApolloX/teleporter_tool/shields/title/)](https://content.minetest.net/packages/ApolloX/teleporter_tool/)` [![ContentDB](https://content.minetest.net/packages/ApolloX/teleporter_tool/shields/title/)](https://content.minetest.net/packages/ApolloX/teleporter_tool/)

**Comment by TurkeyMcMac** [comment]
It looks great! I can actually do some testing since you put it on ContentDB.
